/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Agent */

#ifndef _Included_Agent
#define _Included_Agent
#ifdef __cplusplus
extern "C" {
#endif
#undef Agent_serialVersionUID
#define Agent_serialVersionUID -3215090123894869218LL
#undef Agent_serialVersionUID
#define Agent_serialVersionUID -4100238210092549637LL
#undef Agent_serialVersionUID
#define Agent_serialVersionUID 4974527148936298033LL
/*
 * Class:     Agent
 * Method:    C_GetLocalTime
 * Signature: (LGetLocalTime;)V
 */
JNIEXPORT void JNICALL Java_Agent_C_1GetLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     Agent
 * Method:    C_GetVersion
 * Signature: (LGetVersion;)V
 */
JNIEXPORT void JNICALL Java_Agent_C_1GetVersion
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
